### ISSUE TITLE
switch entity parsing from JSON to YAML or TOML

### ISSUE THREAD

**Issue by majewsky** [majewsky/holo#16]
JSON is a subset of YAML, so we can do that without any disruption. And it enables some nice things like comments and a generally less tedious syntax.

- [ ] exchange JSON parser in `src/entities/scan.go` by an equivalent YAML parser (or add a TOML parser next to it)
- [ ] extend scanning to find `.yaml` (or `.toml`) files in addition to `.json` files
- [ ] show deprecation warning when parsing a `.json` file
- [ ] adjust documentation (manpage, website)
- [ ] make a followup ticket for the next milestone to remove the deprecated recognition of `.json` files

Probably the most complicated part is figuring out the right way to pull in a YAML library as a dependency (right now, we only use the standard library, but that one does not do YAML).

**Comment by atweiden** [comment]
Have you considered [TOML](https://github.com/toml-lang/toml)?

**Comment by majewsky** [comment]
@atweiden Good point. I added the *unclear* label because YAML feels out-of-line with my goal of minimalism. JSON on the other hand is missing some features which I want for other uses inside Holo (most notably multiline strings). TOML seems like a good middle path.
